Support `SKIP LOCKED` and `NOWAIT`
oguimbal/pgsql-ast-parser pull request #129
Opened 2023-04-08 05:59 UTC by arajski

# Description
At the moment the parser doesn't support `SKIP LOCKED` and `NOWAIT`, when working with locking statements (ie `FOR UPDATE`). 
### Example query:
```sql
SELECT id
FROM foo
FOR UPDATE SKIP LOCKED
```
It's quite useful to be able to skip already locked records, especially in a distributed environment

# Change
Added new SkipStatement type and additional syntax to handle `SKIP LOCKED` and `NOWAIT`, which should follow the `FOR` statement. Also added some more tests.

# References
[PostgreSQL Documentation: The Locking Clause](https://www.postgresql.org/docs/current/sql-select.html#SQL-FOR-UPDATE-SHARE)

2023-06-02 09:54 UTC, oguimbal requested changes

2023-06-02 09:54 UTC, oguimbal commented on src/keywords.ts
> +    , "PRECISION", "NOWAIT", "SKIP", "LOCKED"
This is the list of reserved keywords, but those are not keywords.

If you execute something like `create table test(nowait text)`, then it means that `nowait` is not a reserved keyword.

On the contrary, you'll see that `create table test(where text)` will throw a syntax error (coz `where` is a reserved keyword)

You dont need to add words that act as not reserved keywords in this list. You can use them using the pattern that you actually use in `base.ne`

 => remove these from this list, and it should be fine :)

2023-06-02 09:54 UTC, oguimbal commented on src/syntax/base.ne
> +any_keyword -> %kw_all | %kw_analyse | %kw_analyze | %kw_and | %kw_any | %kw_array | %kw_as | %kw_asc | %kw_asymmetric | %kw_authorization | %kw_binary | %kw_both | %kw_case | %kw_cast | %kw_check |
idem, this list should not have changed

2023-06-02 09:54 UTC, oguimbal commented on src/syntax/select.ne
> +select_skip -> (%kw_nowait {% x => track(x, {type: 'nowait'}) %} | %kw_skip %kw_locked {% x => track(x, {type: 'skip locked'}) %})
use `kw_nowait`, `kw_skip` and  `kw_locked` you defined in `base.ne` instead of their reserved keywords counterparts (which start with a `%`)

2023-06-03 11:24 UTC, arajski commented
thanks for clarification 👍  reverted keyword related changes

2023-06-05 08:25 UTC, oguimbal approved these changes

2023-06-05 08:26 UTC, merged

2023-06-05 08:30 UTC, oguimbal commented
released as `pgsql-ast-parser@11.1.0` !

thanks again for the pr